parameters:
  grpc_server_timeout: 10
  grpc_server_reconection_time: 5  
  redis_timeout: 10
  redis_reconection_time: 5
mainMission:
  unitsZones:
    InfAK: 17
    InfRPG: 17
    ArmTrucks: 5
    ArmBMP1: 2
    ArmBMP2: 2
    ArmT55: 2
    ArmT72: 2
    ArmT80: 2
    AAA: [1,3] 
    AATung: [1,3]
    AAStrela1: [1,3]
    AAStrela2: [1,3]
    AAIgla: [2,5]
    AATor: [1,3]
    SAM: [0,1]
capturableRegions:
  names: ['Shoreline', 'Tuapse', 'Goyth', 'Apsheronsk']
  minRegionIncome: 10
  markColorDict: 
    blue: [0, 0, 1, .1]
    red: [1, 0, 0, .1] 
    neutral: [1, 1, 1, .1]
  textColorDict:
    blue: [0, 0, 1, 1]
    red: [1, 0, 0, 1] 
    neutral: [0, 0, 0, 1]